### ISSUE TITLE
"Removed deploy script in favor of publishing via gradle" breaks "runIde"

### ISSUE THREAD

**Issue by tomekw** [AdaCore/Ada-IntelliJ#67]
Hi, I believe this commit: https://github.com/AdaCore/Ada-IntelliJ/commit/c9880dce636ab79bb93b55eb2ac5d7e36fff3c0a breaks the `runIde` task with:

```
> Could not get unknown property 'publishToken' for task ':publishPlugin' of type org.jetbrains.intellij.tasks.PublishTask.
```

Reverting the commit helps but I presume it's not the way to go. Should configuring the `gradle.properties` be described in the README?

**Comment by raja-s** [comment]
You're right! No, general users should not have to configure the `gradle.properties` file.
This should be fixed in #70. Thanks for reporting this :)
