### ISSUE TITLE
Plugin does not seem to work when installed from marketplace

### ISSUE THREAD

**Issue by johnperry-math** [AdaCore/Ada-IntelliJ#80]
I installed the plugin via [the JetBrains marketplace](https://plugins.jetbrains.com/plugin/11931-ada), and it doesn't seem to have set up correctly.

- A new Ada project immediately reports, "Error adding module to project: Project setup started while no project template has been selected"
- In projects that are not Ada projects, it sends a message at startup: "Ada-IntelliJ Plugin - No Compiler Found on the PATH: Please set the gprbuild path in `Run | Edit Configurations`."
- When I open `Run | Edit Configurations`, it is not at all clear how I am supposed to set up a gprbuild path.

Questions:

- Is there any documentation on how to use this when installed from the plugin store? The only documentation I see here indicates how to build it and install it, and appears to assume from then on that things will simply work.
- The plugin documentation does mention Eclipse LSP4J, is this the same as the LSP plugin for Idea, or something different? My impression is that it's something different; if so, do I have to build it myself? or is this just needed for building the plugin?

**Comment by JulienGioux** [comment]
Same old problem and gnastudio still buggy too... Ada will continue to lost developer attraction, years after years.

**Comment by setton** [comment]
Hello @JulienGioux, this extension is no longer maintained.

We're maintaining the Ada Language Server extension for VS Code [here](https://github.com/AdaCore/ada_language_server) - if you find issues with this, don't hesitate to report there.
