### ISSUE TITLE
Plugin is not compatible with current release 2023.1 of IntelliJ

### ISSUE THREAD

**Issue by mounty1** [AdaCore/Ada-IntelliJ#82]
The plugin crashes immediately upon opening a project with Ada source.  Stacktrace attached.  Some basic lexical highlighting (colouring of language keywords in one open source) occurred.
[bug-dump.txt](https://github.com/AdaCore/Ada-IntelliJ/files/12300089/bug-dump.txt)

**Comment by setton** [comment]
Hello @mounty1 - this plugin is not actively maintained, we do not guarantee compatibility.

**Comment by berkeleynerd** [comment]
Just FYI there is ticket over at the AdaCore LSP repo that might track some future work related to Ada language support in JetBrains IDEs. https://github.com/AdaCore/ada_language_server/issues/1155
